### ISSUE TITLE
RiakSearch interface for Yokozuna

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#126]
Create an interface for Yokozuna similar to RiakSearch. Any client communicating with RiakSearch should be able to point to this interface instead and expect everything to work the same. Unimplemented features (eg. updates) should be noops.

The biggest part of this issue will be implementing a webmachine resource, [riak_solr_searcher_wm](https://github.com/basho/riak_search/blob/master/src/riak_solr_searcher_wm.erl), which will query on /solr/INDEX/select

[riak_solr_indexer_wm](https://github.com/basho/riak_search/blob/master/src/riak_solr_indexer_wm.erl) will exist, but be inoperative: /solr/INDEX/update

**Comment by coderoshi** [comment]
Test against #105, #106, #107, #108

**Comment by rzezeski** [comment]
A few ideas:
- Leave the '/search/...' interface alone.
- Add a flag to Yokozuna that changes behavior of `yz_wm_search` when it's listening against `/solr/<index>/select` interface.  That is, the same exact webmachine resource is used for both interfaces but the flag will determine if a function is called to transform the result into something a Riak Search client can understand.  This flag could be called `riak_search_xform` or something like that.
- Find the code that is responsible for creating the webmachine service list and hack it so `yz_wm_search` can pretend it is Riak Search.
- When both Riak Search and Yokozuna are up then Riak Search will handle all queries to `/solr/<index>/select` like it currently does.
- When the user wants to query against Yokozuna but still use Riak Search clients then they would flip 2 bits: 1) set the `riak_search_xform` bit 2) disable/shutdown Riak Search (need to add a command to do that on the fly).  No special flags should need to be sent by client during query requests.  Just flip the bit on the cluster.

Upshot: User can use Riak Search + Yokozuna at same time and query both.  When user decides all data has been migrated and no longer wants to use Riak Search then flip 2 bits and the RS interface now returns results in same format but Yokozuna is actually running the query.  This way there is nothing different about the clients accept the update support won't work.  In future when cilents have full Yokozuna support (or if user wants to use existing Solr clients with the canonical Solr URL) then xform flag can be disabled and it's as if Riak Search never existed.

**Comment by rzezeski** [comment]
I'm going to see if I can create this `riak_search_xform` function today.

**Comment by rzezeski** [comment]
After spending a day on this I'm of the opinion that the server side xform is a bad idea.  I underestimated the nuance in this approach.  I made some headway by using XSLT response write in Solr but looking at the responses more closely I feel there are hard to see corner cases that could bite us.  Considering how precious time is I don't think the bang-for-buck is worth it.  Client using PB to talk to search should already be working except for any cilents using Search + Map-Reuce, but that will be addressed soon.  Any clients using HTTP to talk to search will break.  We would need to update our official clients understand how to parse a Yokozuna response.  It's worth considering just letting the HTTP transport stay broken in the official clients if they also support PB.  This is in line with the push in official clients to all standardize on a binary protocol rather than support multiple transports.  This will have to be taken a client at a time and discussed with clients team and Jon Meredith.  So here are the new action items I propose:
1.  Verify that all official clients can speak to Yokozuna via PB.  This is priority number one.  At least if all clients can speak one transport to Yokozuna than we have a path forward for current users, even if it means telling them to switch transports.  If an official client doesn't have PB/Search support than it's HTTP/Search support will be given priority 1.
2. Discuss with @seancribbs and @jonmeredith about relevance of Search/HTTP for official clients.  If we are moving towards a single protocol world is it really worth the time and effort?  Are we doing work that doesn't matter? (Please note, the HTTP end points will still be available, we just won't use that transport in the clients)
3. If we do find HTTP/Search is needed for our clients then we need to add code that a) allows them to know if they are talking to RS or Yokozuna and b) add appropriate decoders to understand the Yokozuna responses which are different from Riak Search.

**Comment by coderoshi** [comment]
Removing "must" flag since we have settled on only pb support for now.

**Comment by rzezeski** [comment]
Closing this.  There are individual issues to verify each of the clients for the PB interface.
