### ISSUE TITLE
Provide extractors access to the riak object 

### ISSUE THREAD

**Issue by dreverri** [basho/yokozuna#15]
Currently extractors have access to a single value of a riak object. It would be useful for extractor developers to have access to the entire riak object in order to extract metadata. For instance, it would be useful to extract Link headers.

**Comment by rzezeski** [comment]
I purposely made the decision not to pass riak objects to extractors.  I have two main reaons:
1. Riak Object is a KV thing, and I am striving to keep the KV bits as isolated as possible.  This might be a fruitless, non-pragmatic endeavor.
2. When sibling indexing is added it would be the job of the extractor to handle siblings.  Yokozuna wouldn't be able to enforce that it handle all values.

I'm not married to this decision but if extracting metadata is the only concern then I think tagging can handle all cases.  Tagging, in theory, allows you to tag any of the metadata fields.  I qualify that with "theory" because I just realized the current implementation will only check the user meta.  I plan to make this more robust in 0.2, but I could be convinced to sneak it into 0.1 and see how indexing links via tagging turns out.

**Comment by dreverri** [comment]
Perhaps the extractors could be given `{MetaData, Value}` which would be valid for all siblings. With that said, I may be approaching the problem from the wrong direction.

**Comment by rzezeski** [comment]
Currently an extractor maps `Value -> Fields`.  This has proved sufficient thus far.  However, if a use case arises where passing the metadata to the extractor is needed then I'll happily revisit this [1].  Until then I'm going to consider this issue closed.

[1] The links use-case is a valid one but that could be treated the same as "tagging" and done automatically by Yokozuna outside of the extractor.  For now Yokozuna doesn't support links.
