### ISSUE TITLE
Rename default schema when it is created. 

### ISSUE THREAD

**Issue by tatyree** [basho/yokozuna#251]
In the standard workflow, the way a default schema is associated with a bucket:

`curl -XPUT -i 'http://localhost:8098/search/index/my_index'``

_suggests_ it could be accessed like this: 

`curl 'http://localhost:8098/search/schema/my_index'`. 

In fact, it is accessed like this: 

`curl 'http://localhost:8098/search/schema/_yz_default'`.

I'd suggest it would be more intuitive to rename the default to allow it to be accessed via the first call. 

Also, it would be good to have the schema access endpoints documented fully.  I had to read the code to find the GET method.  That said, I may well have missed the reference...

**Comment by rzezeski** [comment]
Well the schema resource is `search/schema/<SchemaName>`. That seems obvious to me since it is the schema resource. You're saying to change it to `search/schema/<IndexName>` so that it retrieves the schema for the index. I can see that argument, and in some ways like it, however it breaks PUT. What does a PUT mean when given an index name for the schema resource?

I think the schema resource should stay as is. The schema name can get retrieved by doing a GET on the index resource `search/index/<IndexName>`, or even just a GET on `search/index` to list all associations.

This resource isn't documented. That definitely needs to be done.

**Comment by tatyree** [comment]
At one level, I think it's that the distinction between the index and the
schema isn't perfectly clear–at least not unless you are pretty au fait
with SOLR.

Maybe it's just a case of putting a note in the documentation that makes
the distintion clear.  That said, even with such a note, I can envisage
getting a lot of "I can't get my schema"-type support queries once it gets
released.

**Comment by rzezeski** [comment]
Sorry I let this ticket rot.

> Maybe it's just a case of putting a note in the documentation that makes
> the distintion clear. 

I think this is the problem in most cases. Our official docs for 2.0
will explain both resources.

> That said, even with such a note, I can envisage
> getting a lot of "I can't get my schema"-type support queries once it gets
> released.

Yes, that's a good point. If you look at ElasticSearch the schema is
part of the index, it doesn't exist outside it (to be pedantic, pretty
sure it's called a "mapping" in ES). Solr is going the same route with
its new managed schema stuff. You send HTTP requests to the index to
read/modify the schema.

That said I think it is too late in the game to change this part of
the API. After 2.0 I'd like to take a step back, not only on the
Search API but also query in general for Riak. I think it could
certainly be cleaner and would like to spend time giving the interface
proper attention. But at this point I think it has to ship as it
stands. And that's not so bad because then feedback can be solicited
and we can figure out what works and what doesn't so we are better
informed for version 2 of the API.

I'm going to close this issue for now as I see no immediate action to
be taken. But please feel free to add more comments if you have
thoughts on what the API should look like.
