### ISSUE TITLE
Cyclic behaviour when creating yokozuna index with broken schema

### ISSUE THREAD

**Issue by oleksiyk** [basho/yokozuna#306]
1) create a schema (`RpbYokozunaSchemaPutReq`), succeeds:

Notice the schema doesn't have a `text` field which is by default is `defaultSearchField`

``` xml
<?xml version="1.0" encoding="UTF-8" ?>
<schema name="test" version="1.5">
  <fields>
    <field name="num" type="long" indexed="true" stored="true"/>

    <field name="_yz_id" type="_yz_str" indexed="true" stored="true" required="true" />
    <field name="_version_" type="long" indexed="true" stored="true"/>
    <field name="_yz_ed" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_pn" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_fpn" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_vtag" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_node" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_rb" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_rk" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_rt" type="_yz_str" indexed="true" stored="true"/>
    <field name="_yz_err" type="_yz_str" indexed="true"/>
  </fields>

  <uniqueKey>_yz_id</uniqueKey>

  <types>
    <fieldType name="_yz_str" class="solr.StrField" sortMissingLast="true" />
    <fieldType name="long" class="solr.TrieLongField" precisionStep="0" positionIncrementGap="0"/>
  </types>
</schema>
```

2) create index (`RpbYokozunaIndexPutReq`), no error returned: 

``` javascript
index: {
      name: 'test-search-index-1392332139243',
      schema: 'test-search-schema-1392332139243' // the schema from step 1
}
```

Solr reports the following:

```
2014-02-14 00:55:40,803 [WARN] <qtp655787180-23>@SolrCore.java:503 [test-search-index-1392332139243] Solr index directory '/usr/local/Cellar/riak/2.0.0-pre11/libexec/data/yz/test-search-index-139233213924
3/data/index' doesn't exist. Creating new index...
2014-02-14 00:55:43,506 [ERROR] <qtp655787180-16>@SolrException.java:108 org.apache.solr.common.SolrException: undefined field text
```

But then Riak will try to create it in background each 60 seconds and fail:

```
2014-02-14 00:55:45,573 [WARN] <qtp655787180-20>@CoreAdminHandler.java:484 Creating a core with existing name is not allowed
2014-02-14 00:55:45,573 [ERROR] <qtp655787180-20>@SolrException.java:108 org.apache.solr.common.SolrException: Core with name 'test-search-index-1392332139243' already exists.
....
2014-02-14 00:56:45,635 [WARN] <qtp655787180-23>@CoreAdminHandler.java:484 Creating a core with existing name is not allowed
2014-02-14 00:56:45,636 [ERROR] <qtp655787180-23>@SolrException.java:108 org.apache.solr.common.SolrException: Core with name 'test-search-index-1392332139243' already exists.
....
2014-02-14 00:57:45,674 [WARN] <qtp655787180-20>@CoreAdminHandler.java:484 Creating a core with existing name is not allowed
2014-02-14 00:57:45,674 [ERROR] <qtp655787180-20>@SolrException.java:108 org.apache.solr.common.SolrException: Core with name 'test-search-index-1392332139243' already exists.
... and so on ...
```

**Comment by coderoshi** [comment]
You should include this in the fields list, it's not optional, due to yokzuna's solrconfig:

```
   <field name="text" type="text_general" indexed="true" stored="false" multiValued="true"/>
```

This error is annoying, since it's a mismatch between yokozuna and solr. YZ knows the core was never created (solr returns a failure), and so attempts to recreated it. But solr actually created the directory anyway, which is why successive attempts are doomed. Moreover, solr doesn't provide a way to test that a schema is valid beforehand. So we check manually that all required fields exist. It looks like we missed one.

In the interim, delete your data/yz/test-search-index-1392332139243 directory, then immediately try and recreate the schema with the above XML element.

**Comment by oleksiyk** [comment]
Yes, I know about `text` field, I mentioned that above. By this issue I actually meant that Riak will go into cycle trying to create already existing Solr index each 60 seconds.

**Comment by oleksiyk** [comment]
I see, thanks

**Comment by rzezeski** [comment]
The cyclic behavior is Yokozuna trying to create the index because it doesn't exist. It is designed that way as the index creation API is not synchronous but rather async + idempotent (or at least it tries to be). There have been changes since pre11 around index creation, one of them was to address an error similar to yours however testing on the latest I was able to get into the loop even after uploading a fixed schema. I believe this could be a change that was made in Solr 4.6.1 that breaks assumptions in the Yokozuna code. I've found several bugs in Solr's Core creation API over the last few Solr releases and each release seems to cause new breakage. That said, I need to dig further to be sure.

While diagnosing this issue I also realized two other things:
- The `solrconfig.xml` is relying on a `text` field when maybe it shouldn't. E.g. the ping and query handlers.
- `yz_events` has a bug where it thinks it's doing a full check every time because it's not updating the previous hash.

**Comment by rzezeski** [comment]
Yokozuna is designed for index creation to be async and idempotent. It
periodically checks the canonical index list with the state of
Solr. If Yokozuna fails to ping the Solr Core (index) then it will
consider it missing and try to create it. That is, Yokozuna will retry
index creation any time the index cannot be pinged. If the Core fails
to initialize due to a bad schema (such as a bad class name) then the
schema can be updated by the user and on the next retry it will try
the new schema.

In this particular case the Core was created and initialized without
error. The issue was that the ping handler was using the default
field, `text`, which didn't exist in the schema. This put the system
in a state where Yokozuna believed that the Core couldn't be pinged so
it tried to create it but Solr would complain it already exists. Path
#313 changes the ping handler to use the field `_yz_id` which MUST
exist in every schema.
