### ISSUE TITLE
Catch-all "*" in default schema XML is problematic

### ISSUE THREAD

**Issue by wbrown** [basho/yokozuna#316]
There are a couple of lines in the default schema that is problematic for people who are potentially just starting out in Riak.

https://github.com/basho/yokozuna/blob/develop/priv/default_schema.xml#L119-L120

``` XML
   <!-- catch-all field -->
   <dynamicField name="*" type="text_general" indexed="true" stored="false" multiValued="true" />
```

I was after a least-obstacle evaluation of Yokozuna, so I used the default fields and typed my fields using the dynamic typing.  I'd noticed that the Yokozuna database was larger than my Riak database, which was unusual and wasteful to me.

I tried turning off the `stored` parameters in the types that I was using, but saw no appreciable difference.

Finally, I noticed the catchall `*` and facepalmed.  Disabling that catchall reduced my Solr database size from gigabytes to dozens of megabytes, and mitigated the `no available vnode` issues that I was seeing with Bitcask.

I appreciate that you're kind of supposed to have your own schema in Solr, but this is error prone for getting started, and gives someone a false impression of Solr's efficiency.

**Comment by rzezeski** [comment]
@wbrown Interesting, the reasoning for adding the catch-all field was so that beginners could search data without learning about the schema or using suffix fields (#95). It will be tough to satisfy everyone. Anyone running Yokozuna in production absolutely needs to create their own schemas that are tailored for the data being indexed.

I guess for me the question is:

Is it better for users to fail to index data and learn about the schema in a very explicit manner or is it better to implicitly index for "ease of use" when first experimenting with Yokozuna?

One thing I don't like about the current situation is it allows users to remain blissfully unaware that most/all of their data is being indexed as text when it shouldn't. If the catch-all was removed users would be forced to understand the mechanisms at play which is a good thing in the long run.

Pinging @coderoshi @jonmeredith @javajolt @bowrocker @tsantero @hectcastro @drewkerrigan @seancribbs @gburd and @michellep for any input on this.

**Comment by coderoshi** [comment]
Yes, I'd been thinking about this as well.  My initial gut reaction was "remove it."  Having slept on it, my current reaction is "remove it."  We can ignore the implications for real production users who know what they're doing, since they'll create their own schemas anyway.  So really we're talking about users who are testing Riak, and also don't read the docs.  So it raises the sorts of complaints we want to deal with.  Either: "I put data in Riak and now I can't search for it, Yokozuna is teh sux," or, "I put data in Riak and it took 200GB of space, Riak is l4me."  Personally, I'd rather deal with the first type of complaint than the second.

vote: remove the catchall.

**Comment by tsantero** [comment]
+1 to removing the catchall. not having it is a more sane default.

**Comment by gburd** [comment]
Can there be a dead simple way to enable it?

riak-admin search-idx bucket enable default

Or whatever.

On Tuesday, February 25, 2014, Tom Santero notifications@github.com wrote:

> +1 to removing the catchall. not having it is a more sane default.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/basho/yokozuna/issues/316#issuecomment-36034543
> .

## 

@gregburd | Basho Technologies | Riak | http://basho.com | @basho

**Comment by tsantero** [comment]
after further thought, my suggestion would be to comment the line out, and explain in the comment that enabling the catchall field will come at the cost of performance and disk.

**Comment by rzezeski** [comment]
> Can there be a dead simple way to enable it?

We could have different default schemas but honestly at that point users would be better served by understanding their data and how to build an appropriate schema.

> my suggestion would be to comment the line out

This would be fine. The other thing to consider is some users will want a catch-all but instead of indexing will want to _ignore_ all fields not explicitly defined. This is needed in cases where the data has regular and irregular fields. Once again, there is no one size fits all in this department and there is no such thing as schemaless (even ElasticSearch has a schema, it just builds it implicitly for you based on convention, but convention can only be so smart).

**Comment by hectcastro** [comment]
If we leave it enabled, I think keeping `stored=false` is a good idea. If we leave it commented out or otherwise disabled, I think that something else has to be done in order to satisfy the case where users just want to send data to Riak and query against Solr for results (without having to think about a schema). Something more than even the default dynamic fields.

The dynamic mapping of JSON datatypes (I think that's how it's done) to an indexing definition in ES is a silent killer feature. For example, people routinely stand up ES clusters and just funnel JSON formatted log data to ES for analysis. Not having to mutate the attribute names (by appending `_s` for strings or `_i` for integers) lowers the barrier to entry a lot. Power users can always define their own mappings later to get the better performance.

Perhaps there is room for an easy and advanced mode? Easy does something to guess at types and dynamically generate a schema (I realize that this is probably easier said than done). Advanced places something similar to the current default schema with the catch-all commented out or disabled?

**Comment by rzezeski** [comment]
@hectcastro Schemaless is neat but I think it may also be a bit of a
gimmick. It has several fallbacks:
- Can't be smart about mapping values to types. It has to pick lowest
  common denominator. This means ints/floats get widest possible
  precision. This means all string values end up as `text_general` which
  may be opposite of what user wants.
- You are indexing _every single_ field. IMO this is not a good
  idea. Most people don't need to index everything. This may work for
  ES because people realize they are storing things in a search-based
  product but people storing Objects in Riak may not think the entire
  value is being indexed.
- If a user stores the same field with different value types then
  objects will fail to index and user will wonder why. I argue this
  gets more likely if you index all fields which is default with these
  "schemaless" modes.
- Let's say we have a smart user who just wants to use schemaless to
  start but then will modify the generated schema. There is no magic
  in Solr, Lucene or Elastic Search that allows you to mutate a field
  and then everything just magically, instantly re-indexes. It will be
  painful. It will break queries. All data will need to be
  re-indexed. It could be horribly expensive for a large index and
  require lots of extra disk space headroom since Lucene is essential
  LSM storage.
- Magic seems like a good idea because then "users don't need to know"
  but in reality they actually need to know and the magic is just
  preventing them from properly indexing their data.

I have ideas to make our index and schema administration better and in
a way that could allow users to take "advantage" of Solr's schemaless
mode. But that's another discussion that would take this issue out of
scope. That said, even if we had schemaless support I would tell all
users to never ever use it anywhere in production...EVER. People
should think about their data before throwing it into Riak/Yokozuna.

Here's two other links that go over schemaless mode and offer some
similar criticism to above:

http://www.ymc.ch/en/why-we-chose-solr-4-0-instead-of-elasticsearch#comment-758

http://searchhub.org/2013/05/21/schemaless-solr-part-1/

Now, all that said, the catch-all field is essentially the same as
Solr's schemaless mode except it's mapping everything to
`text_general` which makes it even worse than schemaless mode. There
are three choices I see:
1. remove it - objects with unspecified fields will fail to index.
2. leave it - all objects will index just fine but maybe all fields
   index as text and user is confused why index is so large and why some
   queries fall to return results.
3. change it to ignored type - all objects will index just fine but
   unspecified fields will be ignored by Solr.

Remember, this is just for the default schema. I think documentation
and tools around creating schemas goes a long way to making the
default schema irrelevant. For example I would like to see a schema
flowchart + d3.js/bash tool built that asks you questions to guide you
towards correct field to use for a given piece of data. Creating
schemas doesn't have to be hard or scary.

One last thought. I think "schemaless" mode in Solr/ES is, in some
ways, analagous to automatically adding secondary indexes to all
columns in a RDBMS table. Yet everyone knows (or should know) that
would be a horribly bad idea.

**Comment by rzezeski** [comment]
Catch-all field changed to `ignored` in #358.
