### ISSUE TITLE
How to handle async protobuf operations: wait? poll? callback?

### ISSUE THREAD

**Issue by xpe** [basho/yokozuna#326]
I'm creating a Yokozuna index via the Riak protobuf interface (calling directly, not through the Java client). The index gets created asynchronously by Solr, right? How do I know when the index will be ready? 

First, I tried waiting an arbitrary amount of time, which I don't like doing. Now, I'm polling, using code that looks like this: https://gist.github.com/xpe/3e2716ee9d6c5f50626a. I don't like polling either.

Is a callback available? Should there be? How do you recommend that applications handle this issue?

**Comment by coderoshi** [comment]
There isn't a callback (I can't see Riak ever providing such a feature), but you can do what our tests do, which is call GET on the index name, and wait for a success. If it fails, wait for a second or so, and try again. We wrote a simple looping function called wait_until to handle this case.

Other than for testing purposes, do you need to create indexes and attempt to use them immediately?

**Comment by xpe** [comment]
Yes, this is for a test suite. I'm doing what you describe: wait for a success inside a polling loop.

**Comment by rzezeski** [comment]
Polling by retrieving the index info, whether by HTTP or PB, will work
in general but is not future proof.  If Solr is up then it will ping
the index but if Solr is down it will just verify that the index is
listed in the cluster metadata.  If Solr is down then the Riak cluster
will also shutdown but there are talks of making this behavior
configurable in the future which will change the semantics.
Furthermore, retrieving the index info only checks the status of the
local node, not the entire cluster.  Our internal tests actually
perform a get across all the nodes in the cluster to determine if an
index is ready.

This is an unfortunate blemish in the current API.  In the future I
would like see index creation as synchronous and atomic, cluster wide.
Until then, however, the best that can be done is polling.

That said, if you think about it async creation is not much different
from random failure due to JVM issues.  This is why AAE is so
important.  If KV writes fail to index it will be caught by AAE and
indexing will be retried at a later time.  If you start writing to an
indexed bucket before the index is ready across all nodes then AAE
will notice and eventually repair those indexes.  You'll just to
deal with non-deterministic results until that repair happens.

I'm closing this issue as there is no immediate action to take.
