### ISSUE TITLE
Extend a client to work for Yokozuna

### ISSUE THREAD

**Issue by coderoshi** [basho/yokozuna#37]
As we push closer to a production release, we should have a Riak client or two which can manage/query YZ. I lean toward Ruby via HTTP, but any will do.

**Comment by rzezeski** [comment]
Any client that currently supports Riak Search over HTTP can start querying Yokozuna once it starts listening on the canonical Solr resource.  I.e. `/solr/<index>/select`.  I'll add an issue for that.

That is an easy start but Solr has many more features than Riak Search.  How do we expose them going forward in our _Riak_ clients?  Do we want to be very specific about what can be passed (e.g. which query params can be passed)?  That could be very tedious.  Or do we want to be general and act as a mediator between the user and Solr?  Allowing less client code but chance for invalid calls.

It's worth thinking about how we can integrate existing Solr clients as that could save us a lot of time, both now and in the future (it could also cause headaches as someone else's bugs are now ours too).  E.g. we could integrate the SolrJ client with our java client.

You are right, we need to start working on client support now, not later.

**Comment by coderoshi** [comment]
After speaking with @seancribbs I think we can hold off on this until after YZ is released. #38 allows for querying YZ at parity with Search, which brings us to the goal of being a suitable replacement. Search doesn't support any indexing/administration via PB, so we'd have to create new messages anyway.

This is certainly a worthwhile goal in the future, but marking it as "must" might be a bit heavy-handed right now.

**Comment by rzezeski** [comment]
This issue was a bit vague to being with.  I say we close it with #38.  But making sure the main clients work with Yokozuna is a "must" for getting it into mainline.  Both HTTP and PB should work.  If those existing clients only support the limited RS Solr-like interface that is fine.  The key is that users can upgrade and their queries still work.

I believe the following clients are the main ones to support.
- Java
- Ruby
- Erlang
- Python

It should be easy enough to run their respective unit/integration tests and make sure they work.  However, I believe some of them use the RS Solr-like update resource.  Yokozuna doesn't support that ATM, it only indexes KV data.  So those tests would break.  Other than that things should hopefully "just work", but we still need to verify.

I'll go ahead and create an issue for each client to verify that it has parity with RS on the query side of things.
