### ISSUE TITLE
Sibling objects with curly brace keys are not deleted from YZ when deleted from KV

### ISSUE THREAD

**Issue by jhmullen** [basho/yokozuna#370]
If you insert an object into a search-enabled bucket that has curly braces in its key (e.g., '{123}') and that object has siblings, a DELETE issued to that object will remove the object from Riak KV, but NOT from its associated index.  Subsequent sibling creation and deletes will continually grow the quantity of indexed objects in search results.
#### Steps for reproducing:

1) Insert a key with curly braces such as `{123}` into a search-enabled bucket with `allow_mult=true` using the default schema.

2) Insert the same object at least one more time.  

3) Perform an exact match search to observe that numFound=siblingCount (as expected).

4) Delete the object 

5) Perform a GET to observe 404 (correct)

6) Perform search again, noting that numFound=siblingCount instead of 0.  Subsequent runs will increase this number indefinitely.

A simple shell script example is available here:

https://gist.github.com/jhmullen/82c0227ae9b4c9e599b2
#### Expected Behavior:

Deletion of this sibling object from KV should remove all associated indexes in Search.

**Comment by rzezeski** [comment]
The issue is caused by Yokozuna's failure to deal with reserved
characters in the Lucene query syntax [[1]](http://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping%20Special%20Characters).  Not only does the
current code fail to escape them but it also mysteriously URL encodes
the key which is a bug in and of itself.  I have a reproducer and am
working on the fix.

**Comment by coderoshi** [comment]
@rzezeski https://github.com/basho/yokozuna/blob/develop/src/yz_solr.erl#L335 the code does escape the key, to fix the issue with reserved word escapes https://github.com/basho/yokozuna/commit/c147db7f8c9d426a069e639f1e1ab753837da3ad#diff-1933b9092cbac0de03ef337894712bfdR105

**Comment by rzezeski** [comment]
@coderoshi It turns out this is not enough.  The backslash and double
quotes need to be escaped individually.  The binary to list causes
failures for keys with non-latin characters.  Finally the url encoding
should not be done because the keys are not stored url encoded and the
query is being sent as JSON, not url encoded.  I am wrapping up a test
and fix for all this tomorrow.
