### ISSUE TITLE
In rare cases _yz_id is not unique

### ISSUE THREAD

**Issue by rzezeski** [basho/yokozuna#406]
Currently the unique id, `_yz_id` is built like so:

``` erlang
<<BType/binary,"_",BName/binary,"_",Key/binary,"_",Partition/binary>>.
```

Or if a sibling value:

``` erlang
<<BType/binary,"_",BName/binary,"_",Key/binary,"_",Partition/binary,"_",Sibling/binary>>.
```

Full code: https://github.com/basho/yokozuna/blob/develop/src/yz_doc.erl#L52

Given the right combination of type and bucket names, all indexing under the **SAME INDEX**, there could be unique KV objects which collide on `_yz_id`.  This is bad because `_yz_id` is used as the unique id in Solr.  When two writes are done to the same unique id the later one wins.  In the case of a collision this could mean one of the object's indexes would be missing from Solr.

Here is an example of such a combination:

Type1 = `type_bucket`
Bucket1 = `yay`
Type2 = `type`
Bucket2 = `bucket_yay`
Key = `k`
Partition = `0`

ID1 = `type_bucket_yay_k_0`
ID2 = `type_bucket_yay_k_0`

Thanks to @engelsanchez for finding this bug.

**Comment by jonmeredith** [comment]
We may be wise to prefix all ids with a version number, like '1' so we can find/filter later?

**Comment by coderoshi** [comment]
I think we should choose a less common character as a separator, like `*`. Then, url encode types/buckets/keys (TBKs) `*` (%2A) and `%` (%25) chars. This will halt any chance of `*` overlapping ids, and also encoding `%` will deal with the case of someone having the literal string `%2A` in an id (it would encode to `%252A`). And since `*` and `%` are relatively less commonly used characters for TBKs, it will reduce the cases of encoding.

I'm ok with prefixing with a number

Type1 = `type*bucket`
Bucket1 = `yay`
Type2 = `type`
Bucket2 = `bucket*yay`
Key = `k`
Partition = `0`

ID1 = `1*type%2Abucket*yay*k*0`
ID2 = `1*type*bucket%2Ayay*k*0`

**Comment by coderoshi** [comment]
Actually, no need to even do real url encoding, save a couple chars... `*`=`%1`, `%`=`%2`
