### ISSUE TITLE
Search tutorial problems

### ISSUE THREAD

**Issue by andytill** [basho/yokozuna#414]
I've had some problems with the tutorial at http://docs.basho.com/riak/2.0.0beta1/dev/using/search/.

After adding the Thunder Cats to Riak, the cats bucket still does not exist, nor do the values.  Running a search returns no results.  When I add a key to the cats bucket in the usual way, without the bucket type e.g.

```
curl -XPUT $RIAK/riak/cats/john -H "content-type: application/json" -d '{"name_s":"john", "age_i":300, "leader_b":false}'
```

The bucket is now created.  When I run the search, twelve results are returned.  This is probably the number of times I tried to add the Thunder Cats trying to get it to work.  Now the bucket is created, adding a key using the `/types/` URL still doesn't add the key to the bucket but an extra result is returned from the search.

This is running Riak installed from riak_2.0.0beta1-1_amd64.deb, Ubuntu 13.10, java version "1.7.0_55".

**Comment by coderoshi** [comment]
You can't use the old style URLs. The example does't use the old style `/riak/cats/john`, but rather `/buckets/cats/keys/john`.

Also, different `/types/` are entirely different namespaces. `/types/AAA/buckets/X/keys/Y` is not in any way related to `/types/BBB/buckets/X/keys/Y`, even if the bucket and key names match. Since the buckets aren't related, you need to set an index to base type (all buckets under that type will inherit that setting and thus be indexed) or set an index for each bucket in each type.

As for multiple values, that's probably because you have `allow_mult` set to true. Every sibling is indexed. So if you add a value and 11 conflicts, you'll get 12 results back until you resolve those conflicts back to a single value. When you do, the index will repair as well.

**Comment by andytill** [comment]
Hi @coderoshi 
Thanks, I tried a few things to get it working so it might have been coincidental that I tried the old URL.
